### ISSUE TITLE
Spilt SCM

### ISSUE THREAD

**Issue by ChristophLHR** [mc-cc-scripts/script-manager#30]
Currently the SCM is only in one big file, which makes maintaining and upgrading the SCM harder and harder.
Therefore we should split the SCM functionality into multiple parts, each taking specific responsibilities.
For Example: 
- Download & Install
- Local-Script-Manager (Responsable for the JSON)
- UI
- ...
- new Features to come 

Additionally, there should be an installer within git directly, which enables us to be almost completely Independent from Pastebin.

**Comment by ColdIV** [comment]
> Additionally, there should be an installer within git directly, which enables us to be almost completely Independent from Pastebin.

"almost" because we would still need a script for the initial install, right? A script that runs the "install script" within the repository. Updates can then be handled via SCM itself.

Sounds good. We should put everything in a proper directory then. I'd still prefer not to use "external dependencies" for the SCM. There are a few functionalities we use in SCM that we also have as a library, I think those should stay separated.
